version: '3'

services:
  app:
    image: golang:1.10-alpine3.9
    command: go run ./cmd/bot/bot.go
    volumes:
      - $GOPATH/src/:/go/src/
    working_dir: /go/src/github.com/stdevMac/Mybot
    networks:
    - redis-net
    depends_on:
      - redis
    links:
      - "redis:redis"

  redis:
    image: redis
    container_name: redis_new
    expose:
    - 6379/tcp
    restart: always
    networks:
    - redis-net
    volumes:
      - redis_db:/data


networks:
  redis-net:
    driver: bridge

volumes:
  redis_db: