version: '3'

services:
  app:
    image: golang:1.12.6-alpine3.10
    command: go run ./cmd/bot/bot.go
    container_name: app
    restart: always
    volumes:
      - $GOPATH/src/:/go/src/
    working_dir: /go/src/github.com/stdevMac/Recharge_bot
    depends_on:
      - redis

  redis:
    image: redis
    container_name: redis
    expose:
    - 6379/tcp
    restart: always
    volumes:
      - redis_db_bot:/data

volumes:
  redis_db_bot:
    external: true
